site_name: Physically Based Rendering
site_url: https://pbrtv4.chenz01.top
theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css